### ISSUE TITLE
Nothing returned from lapd.File digitizers 

### ISSUE THREAD

**Issue by rdorst** [BaPSF/bapsflib#59]
I am not sure if something has changed with the upgrades to LAPD, but when I try the following it does not return anything

src = 'run002_bfield_xz_plane.hdf5'
with lapd.File(src,silent=True)  as sf:
        
        src_digitizers = sf.digitizers

src_digitizers = [].

Traceback (most recent call last):

  File "/Volumes/Samsung_2/Python/lapd_sept2019_process.py", line 194, in <module>
    process(data_dir, overwrite_raw=True, overwrite_full=True, run=runs3, probe=['c14'], rawsource='LAPD')

  File "/Volumes/Samsung_2/Python/lapd_sept2019_process.py", line 48, in process
    rawfile =  lapd.lapdToRaw(run, probe[0], hdf_dir, csv_dir, rawfile, trange=trange, verbose=True)

  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/uclahedp/load/lapd.py", line 115, in lapdToRaw
    digi = src_digitizers['SIS crate'] #Assume this id the digitizer: it is the only one

KeyError: 'SIS crate'

**Comment by rocco8773** [comment]
So, I don't completely understand this yet, but this is what I think is happening (ref screen shot bellow)...

1. The SIS crate configuration "sisconf-fastdiz-4ch" has a configuration group for the SIS 3302 (`Raw data + config/SIS crate/sisconf-fastdiz-4ch/SIS crate 3302 configurations[0]`), but none of the channels for thee 3302 are activated.  This is leading to the UserWarning thrown by https://github.com/BaPSF/bapsflib/blob/1121b3500f83612833e2de511a9c07d0a3fe9a8d/bapsflib/_hdf/maps/digitizers/siscrate.py#L704-L709

2. Since a configuration for the 3302 is found but it is NULL since no channels are enabled a mapping error is thrown by https://github.com/BaPSF/bapsflib/blob/1121b3500f83612833e2de511a9c07d0a3fe9a8d/bapsflib/_hdf/maps/digitizers/siscrate.py#L499-L505

3. Because of this thrown error, the code does not have "confidence" in the mapping and thus discards it.  That why you do not see it in `f.digtizers`.

![image](https://user-images.githubusercontent.com/29869348/128443263-300aceec-c897-44c9-ac31-4fbe2dc970f8.png)

**Comment by rocco8773** [comment]
Alright, I think I have a patch for you.  I have it in a branch on my personal account, https://github.com/rocco8773/bapsflib/tree/patch_siscrate_mapping.  So, install that branch on you local machine and let me know if it works for you.  If so, then I'll update the tests and open a PR to bring it into `master`.

**Comment by svincena** [comment]
Just for more info:
There were no changes to the SIS crate part of the acquisition code in current release since
the last time your group took data. However, the ability to have a board active but
with no active channels has always been there and is used by some people to keep
channel name information from disappearing if the board itself gets de-selected.


-Steve

**Comment by rdorst** [comment]
Hello,
This seems to have worked for me, thank you.

**Comment by rocco8773** [comment]
@svincena Yeah, I think this is exactly what was happening. The original mapping assumed a board would only be configured if channels were activated. Wasn't too difficult to fix.

@rdorst Cool! I'll work this bro the master branch then. I'll ping you when that happens.

**Comment by jpilgram** [comment]
Hi!

I just wanted to let you know that I installed the latest version of bapslib (1.0.1) and it did not include the patch needed to address this issue. I had to get the files from Bobby in order to get my code working.

**Comment by rocco8773** [comment]
@jpilgram The modifications you need have yet to make it to a release.  You will need to directly install the `master` branch form GitHub.  You can find the instructions [here](https://bapsflib.readthedocs.io/en/latest/installation.html#installing-directly-from-github).
